### ISSUE TITLE
运行不通过的问题咨询

### ISSUE THREAD

**Issue by Crystal521** [blahgeek/ray-tracing#1]
![default](https://cloud.githubusercontent.com/assets/12197955/22413477/2ed6ad6c-e6f3-11e6-8cc3-eef3babd45ca.png)
您好，我运行了您的程序，出现了这样的错误，请问原因是什么呢？

**Comment by blahgeek** [comment]
hi你好 抱歉大过年的回复的比较晚

这个代码实在是太过于古老了…问我估计也没啥用了😂
当时应该是能跑的，可能是一些平台相关的问题吧，我当时在Linux上开发的，可以单步调试看看

PS我后来写了一个OpenCL版本的，https://github.com/blahgeek/hptracing，代码风格可能更加好一点，效果也更好…

多谢关注~
